//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopShoes123
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrdersProducts = new HashSet<OrdersProducts>();
        }
    
        public int OrderID { get; set; }
        public Nullable<double> OrderDate { get; set; }
        public Nullable<double> DeliveryDate { get; set; }
        public Nullable<int> AddressPointID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> CodeToReceive { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
    
        public virtual AddressPointOfIssues AddressPointOfIssues { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersProducts> OrdersProducts { get; set; }
    }
}
